"""initial migration

Revision ID: 332f49544be6
Revises: 
Create Date: 2023-08-22 07:44:01.980624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332f49544be6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_constraint('reply_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reply_post_id_fkey', 'class', ['post_id'], ['id'])

    # ### end Alembic commands ###
