"""classes-people relationship

Revision ID: ddd382bb4852
Revises: 332f49544be6
Create Date: 2023-08-30 09:17:42.481626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd382bb4852'
down_revision = '332f49544be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    with op.batch_alter_table('classes_people', schema=None) as batch_op:
        batch_op.create_index('pupils', ['class_id', 'user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes_people', schema=None) as batch_op:
        batch_op.drop_index('pupils')

    op.create_table('classes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name='classes_class_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='classes_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'class_id', name='classes_pkey')
    )
    # ### end Alembic commands ###
